
#PATH=$PATH:/c/devkitpro/devkitPSP/bin
PATH:=${PATH}:/home/yoyz/local/pspdev/

TARGET = lgpt

EXTRA_TARGETS = EBOOT.PBP
PSP_EBOOT_TITLE = LittleGPTracker
PSP_EBOOT_ICON = $(PWD)/psp_icon.png
PSP_EBOOT_PIC1 = $(PWD)/psp_bg.png

include $(PWD)/psp_rules

PSPSDK=$(shell ${PSPDEV}/bin/psp-config --pspsdk-path)
PSPBIN = $(PSPSDK)/../bin

CFLAGS	:=	-O3 -G0 -Wall -DPLATFORM_$(PLATFORM) -DNDEBUG -DCPP_MEMORY -I$(PWD)/../sources -I$(PSPSDK)/include -fpermissive -D_DEBUG

CXXFLAGS:=	$(CFLAGS) -fexceptions -fno-rtti

EXTENSION:= elf

LIBS = -L${PSPDEV}/psp/sdk/lib -lSDL_image -lpng -lz -lstdc++
LIBS += -lSDL -lGL -lGLU -lglut -lpspvfpu -lm -lpspdebug -lpspgu -lpspctrl -lpspge -lpspdisplay -lpsphprm -lpspsdk -lpsprtc -lpspaudio -lc -lpspuser -lpsputility -lpspkernel -lpspnet_inet -ljpeg -lpspirkeyb -lpsppower -lpsppower_driver

