
DEVKITARM=/c/devkitGP2X
DEVKITARM=/opt/open2x/

DEVKITPRO=$(DEVKITARM)/..

TOOLPATH=$(DEVKITARM)/bin
PREFIX		:=	arm-linux-
PREFIX		:=      arm-open2x-linux-
SDL_BASE = C:/devkitGP2X/bin/arm-linux-
SDL_BASE = ${DEVKITARM}

include $(PWD)/gp2x_rules

CFLAGS	:=	`$(SDL_BASE)sdl-config --cflags` -DNDEBUG -O2 -Wall -DCPP_MEMORY -DPLATFORM_$(PLATFORM) -I$(PWD)/../sources -D__LINUX_OSS__ 
CFLAGS	:=	-I${DEVKITARM}/include -DNDEBUG -O2 -Wall -DCPP_MEMORY -DPLATFORM_$(PLATFORM) -I$(PWD)/../sources -D__LINUX_OSS__ 

CXXFLAGS:=	$(CFLAGS)

EXTENSION:= gpe

LIBS	:=  -L$(PWD)/../libs/GP2XSDL/ -lSDL -lpthread 


LIBDIRS	:=	$(DEKVITPRO)/lib
